using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UIElements;
using UnityEngine.Rendering.Universal;
using static Playground.UIFactory;
namespace Playground {
public class GameHUD:MonoBehaviour {
 public bool Paused;public float HitUntil;public VisualElement Root{get;private set;}public int RefreshCount{get;private set;}
 Arena a;UIDocument document;PanelSettings settings;VisualElement hud,pause,results,center,hit,crosshair,research;Label score,round,connection,decision,latency,banner,subline,held,dodge,interaction,edge,resultTitle,resultInfo,perf;
 Label[] left=new Label[9],right=new Label[9],counts=new Label[10];VisualElement[] bars=new VisualElement[10];Button rematch;float nextRefresh,smoothFrame;bool wasOver,statsVisible;Camera sceneCamera;
 static readonly string[] actionNames={"Approach","Retreat","Push","Grab","Throw","Dodge left","Dodge right","Move to safety","Take cover","Jump"};
 void Start(){a=Arena.Instance;sceneCamera=Camera.main;settings=ScriptableObject.CreateInstance<PanelSettings>();settings.scaleMode=PanelScaleMode.ScaleWithScreenSize;settings.referenceResolution=new Vector2Int(1440,900);settings.screenMatchMode=PanelScreenMatchMode.MatchWidthOrHeight;settings.match=.5f;settings.themeStyleSheet=Resources.Load<ThemeStyleSheet>("UI/Theme");document=gameObject.AddComponent<UIDocument>();document.panelSettings=settings;Root=document.rootVisualElement;Root.AddToClassList("screen");Root.styleSheets.Add(Resources.Load<StyleSheet>("UI/Playground"));Root.pickingMode=PickingMode.Ignore;BuildHUD();BuildPause();BuildResults();research=Box(Root,"research-layer");a.Research.Build(research);Visible(research,false);SetQuality(PlayerPrefs.GetInt("presentation_quality",0));Refresh();}
 void BuildHUD(){hud=Box(Root,"hud");hud.pickingMode=PickingMode.Ignore;var top=Box(hud,"topbar");top.pickingMode=PickingMode.Ignore;var brand=Box(top,"brand card row");var icon=new Image{image=Resources.Load<Texture2D>("UI/AppIcon")};icon.AddToClassList("brand-icon");brand.Add(icon);var wordmark=Box(brand);Text(wordmark,"PHYSICS","eyebrow cyan");Text(wordmark,"PLAYGROUND","brand-title");
 var scoring=Box(top,"score card");var line=Box(scoring,"row scoreline");Text(line,"YOU","cyan score-side");score=Text(line,"0  :  0","score-number");Text(line,"LAYA","orange score-side");round=Text(scoring,"ROUND 1  /  FIRST TO 5","eyebrow centered");
 var ai=Box(top,"ai card");connection=Text(ai,"●  LOCAL LAYA","eyebrow cyan");decision=Text(ai,"Ready when you are","decision");latency=Text(ai,"Waiting for first decision","muted");
 center=Box(hud,"announcement");banner=Text(center,"3","countdown");subline=Text(center,"SEND LAYA OFF. STAY ON THE ROOF.","eyebrow centered");
 var bottom=Box(hud,"bottom");bottom.pickingMode=PickingMode.Ignore;var lower=Box(bottom,"row lower");var status=Box(lower,"card player-status");held=Text(status,"HANDS FREE","cyan status-title");dodge=Text(status,"Dodge ready  /  SHIFT","muted");var hint=Box(lower,"hint");edge=Text(hint,"","edge");interaction=Text(hint,"F   PUSH","interaction");var quick=Box(lower,"quick");Text(quick,"ESC   Pause     F2   Experiment lab","muted");Text(quick,"TAB   Match statistics","muted");Text(bottom,"WASD  Move     MOUSE  Look     SPACE  Jump     SHIFT  Dodge     E  Grab / drop     CLICK  Throw     F  Push","controls");
 hit=Box(hud,"impact");hit.pickingMode=PickingMode.Ignore;crosshair=Box(hud,"crosshair");crosshair.pickingMode=PickingMode.Ignore;Text(crosshair,"+","reticle");}
 void BuildPause(){pause=Box(Root,"scrim");var card=Box(pause,"pause-card");Text(card,"TAKE A BREATHER","eyebrow cyan");Text(card,"Your next move\ncan wait.","pause-title");Text(card,"The roof will still be here.","muted pause-subtitle");Button(card,"Resume game   →",()=>Pause(false),"primary large");Button(card,"Start a new match",NewMatch,"large");Button(card,"Experiment lab",()=>a.Research.Show(),"large");var quality=new DropdownField("Graphics",new System.Collections.Generic.List<string>{"Balanced · 60 FPS","High · 120 FPS"},PlayerPrefs.GetInt("presentation_quality",0));quality.RegisterValueChangedCallback(e=>SetQuality(quality.index));card.Add(quality);perf=Text(card,"","muted performance");Button(card,"Quit to desktop",()=>Application.Quit(),"quiet");Text(card,"ESC TO RESUME","eyebrow centered");Visible(pause,false);}
 void BuildResults(){results=Box(Root,"scrim");var card=Box(results,"results-card");Text(card,"THE MATCH, IN NUMBERS","eyebrow cyan");resultTitle=Text(card,"Match snapshot","section-title");var columns=Box(card,"row");var table=Box(columns,"stats-table");var headings=Box(table,"stat-row");Text(headings,"PERFORMANCE","stat-name eyebrow");Text(headings,"YOU","stat-value cyan");Text(headings,"LAYA","stat-value orange");string[] labels={"Round wins","Self ring-outs","Grabs / throws","Throw hit rate","Successful pushes","Dodges","Time near edge","Average edge distance","Opponent-caused ring-outs"};for(int i=0;i<labels.Length;i++){var row=Box(table,"stat-row");Text(row,labels[i],"stat-name");left[i]=Text(row,"0","stat-value cyan");right[i]=Text(row,"0","stat-value orange");}var distribution=Box(columns,"distribution");Text(distribution,"LAYA'S CHOICES","eyebrow");for(int i=0;i<10;i++){var row=Box(distribution,"action-row");Text(row,actionNames[i],"action-name");var track=Box(row,"bar-track");bars[i]=Box(track,"bar-fill");counts[i]=Text(row,"0","action-count");}
 resultInfo=Text(card,"","muted result-info");var footer=Box(card,"row result-footer");rematch=Button(footer,"Play again   →",NewMatch,"primary");Button(footer,"Experiment lab / exports",()=>a.Research.Show());Text(footer,"Hold TAB during play to inspect","muted");Visible(results,false);}
 void NewMatch(){a.Research.Close(false);Pause(false);a.Match.NewMatch();Refresh();}
 public void Pause(bool value){Paused=value;Time.timeScale=value?0:1;if(!a)a=Arena.Instance;if(a&&a.Human)a.Human.GetComponent<HumanInput>().Capture(!value&&a.Match.Phase!=RoundPhase.MatchOver);if(pause!=null)RefreshVisibility();}
 public void SetQuality(int index){index=Mathf.Clamp(index,0,1);PlayerPrefs.SetInt("presentation_quality",index);QualitySettings.vSyncCount=0;Application.targetFrameRate=index==0?60:120;if(UnityEngine.Rendering.GraphicsSettings.currentRenderPipeline is UniversalRenderPipelineAsset urp){urp.renderScale=index==0?.85f:1;urp.msaaSampleCount=index==0?2:4;}}
 void Update(){if(Root==null)return;smoothFrame=Mathf.Lerp(smoothFrame,Time.unscaledDeltaTime,.06f);bool over=a.Match.Phase==RoundPhase.MatchOver;if(over&&!wasOver){a.Human.GetComponent<HumanInput>().Capture(false);Refresh();}wasOver=over;RefreshVisibility();Visible(hit,Time.unscaledTime<HitUntil&&!Paused);if(!Paused&&Time.unscaledTime>=nextRefresh){nextRefresh=Time.unscaledTime+.1f;Refresh();}if(Paused&&Time.unscaledTime>=nextRefresh){nextRefresh=Time.unscaledTime+.5f;Set(perf,$"{1/Mathf.Max(.001f,smoothFrame):0} FPS   ·   {smoothFrame*1000:0.0} ms / frame");}UpdateAim();}
 void RefreshVisibility(){bool lab=a.Research.Open;bool stats=!lab&&!Paused&&((Keyboard.current?.tabKey.isPressed??false)||a.Match.Phase==RoundPhase.MatchOver);if(stats&&!statsVisible)RefreshResults();statsVisible=stats;Visible(research,lab);Visible(pause,Paused&&!lab);Visible(results,stats);Visible(hud,!lab);}
 void Refresh(){RefreshCount++;Set(score,$"{a.Match.HumanWins}  :  {a.Match.AIWins}");Set(round,$"ROUND {a.Match.Round}   /   FIRST TO {a.Match.WinsRequired}");bool offline=a.Client.Status.Contains("unavailable");Set(connection,!a.Experiments.Ready?"●  PROFILE NEEDS ATTENTION":offline?"●  LOCAL MODEL OFFLINE":"●  LOCAL LAYA / SYSTEM 1");connection.EnableInClassList("orange",offline||!a.Experiments.Ready);Set(decision,!a.Experiments.Ready?"Open F2 to review settings":a.Client.Status.Contains("No legal")?"No legal actions · waiting":a.Client.Busy?"Choosing the next move…":a.Brain.ExecutedDecisions>0?actionNames[(int)a.Executor.Selected]:"Ready when you are");Set(latency,a.Telemetry.RecordingError!=null?"Recording error · check storage":offline?"Neutral wait · reconnecting":$"{a.Client.LastLatency:0} ms  model latency");Set(held,a.Human.Held?"HOLDING / "+a.Human.Held.Kind.ToUpperInvariant():"HANDS FREE");Set(dodge,Time.time<a.Human.StunnedUntil?"Recovering balance…":Time.time<a.Human.NextDodge?$"Dodge in {a.Human.NextDodge-Time.time:0.0}s":"Dodge ready  /  SHIFT");var nearest=a.Human.Held?null:a.Human.Nearest();Set(interaction,a.Human.Held?"CLICK   THROW "+a.Human.Held.Kind.ToUpperInvariant():nearest?"E   GRAB "+nearest.Kind.ToUpperInvariant():"F   PUSH");Set(edge,a.Human.Edge<1.8f?"OPEN EDGE · WATCH YOUR STEP":"");bool countdown=a.Match.Phase==RoundPhase.Countdown;Visible(center,countdown||a.Match.Phase==RoundPhase.Winner||a.Match.Practice);Set(banner,a.Match.Practice?"EXECUTOR LAB":countdown?Mathf.CeilToInt(a.Match.PhaseEnds-Time.time).ToString():a.Match.Announcement);banner.EnableInClassList("round-message",!countdown);Set(subline,a.Match.Practice?"PRACTICE / SCORING DISABLED":countdown?"SEND LAYA OFF. STAY ON THE ROOF.":"NEXT ROUND IN A MOMENT");if(statsVisible)RefreshResults();}
 void RefreshResults(){var h=a.Human;var l=a.AI;Set(resultTitle,a.Match.Phase==RoundPhase.MatchOver?a.Match.Announcement:"Match snapshot");string[] lv={a.Match.HumanWins.ToString(),a.Match.HumanSelfOuts.ToString(),$"{h.Grabs} / {h.Throws}",h.Throws>0?$"{100f*h.Hits/h.Throws:0}%":"—",h.Pushes.ToString(),h.Dodges.ToString(),$"{h.EdgeTime:0.0}s",$"{h.EdgeSum/Mathf.Max(.01f,h.Samples):0.0} m",a.Match.HumanEnvironmentalKOs.ToString()};string[] rv={a.Match.AIWins.ToString(),a.Match.AISelfOuts.ToString(),$"{l.Grabs} / {l.Throws}",l.Throws>0?$"{100f*l.Hits/l.Throws:0}%":"—",l.Pushes.ToString(),l.Dodges.ToString(),$"{l.EdgeTime:0.0}s",$"{l.EdgeSum/Mathf.Max(.01f,l.Samples):0.0} m",a.Match.AIEnvironmentalKOs.ToString()};for(int i=0;i<9;i++){Set(left[i],lv[i]);Set(right[i],rv[i]);}int max=1;foreach(int n in a.Telemetry.Distribution)max=Mathf.Max(max,n);for(int i=0;i<10;i++){Set(counts[i],a.Telemetry.Distribution[i].ToString());bars[i].style.width=Length.Percent(100f*a.Telemetry.Distribution[i]/max);}Set(resultInfo,$"{a.Telemetry.DecisionCount} executed decisions   ·   {a.Telemetry.TotalLatency/Mathf.Max(1,a.Telemetry.DecisionCount):0} ms mean model latency   ·   F3 exports full decision details");Visible(rematch,a.Match.Phase==RoundPhase.MatchOver);}
 void UpdateAim(){bool show=!Paused&&a.Match.Phase==RoundPhase.Fight&&a.Human.Held&&sceneCamera;Visible(crosshair,show);if(!show)return;float speed=a.Human.Held.Body.mass>10?14:18,flight=6/speed;var point=a.Human.transform.position+Vector3.up*1.25f+a.Human.transform.forward*1.05f+a.CameraRig.Aim*speed*flight+Physics.gravity*(.5f*flight*flight);var screen=sceneCamera.WorldToScreenPoint(point);Visible(crosshair,screen.z>0);crosshair.style.left=screen.x/Screen.width*Root.resolvedStyle.width-10;crosshair.style.top=(1-screen.y/Screen.height)*Root.resolvedStyle.height-10;}
 void OnApplicationFocus(bool focus){if(!focus&&a&&System.Array.IndexOf(System.Environment.GetCommandLineArgs(),"--pg-benchmark")<0)Pause(true);}
 void OnDestroy(){Time.timeScale=1;if(settings)Destroy(settings);}
}
}
