using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UIElements;
using UnityEngine.Rendering.Universal;
using static Playground.UIFactory;
namespace Playground {
public class GameHUD:MonoBehaviour {
 public bool Paused;public float HitUntil;public VisualElement Root{get;private set;}public int RefreshCount{get;private set;}
 Arena a;UIDocument document;PanelSettings settings;VisualElement hud,pause,results,center,hit,crosshair,research,aiPanel,tutorialPanel,threat;Label tutorialText,threatText,pushStatus;VisualElement dodgeFill,pushFill;bool diagnostics,help;Label score,round,connection,decision,latency,banner,subline,held,dodge,interaction,edge,resultTitle,resultInfo,perf;
 Label roundClock,resultScore;Label leftTitle,rightTitle,leftStatsTitle,rightStatsTitle,distributionTitle,secondAI,controls;DropdownField distributionPlayer;
 Label[] left=new Label[9],right=new Label[9],counts=new Label[10];VisualElement[] bars=new VisualElement[10];Button rematch;float nextRefresh,smoothFrame;bool wasOver,statsVisible;Camera sceneCamera;
 static readonly string[] actionNames={"Approach","Retreat","Push","Grab","Throw","Dodge left","Dodge right","Move to safety","Take cover","Jump"};
 void Start(){a=Arena.Instance;sceneCamera=Camera.main;settings=ScriptableObject.CreateInstance<PanelSettings>();settings.scaleMode=PanelScaleMode.ScaleWithScreenSize;settings.referenceResolution=new Vector2Int(1440,900);settings.screenMatchMode=PanelScreenMatchMode.MatchWidthOrHeight;settings.match=.5f;settings.themeStyleSheet=Resources.Load<ThemeStyleSheet>("UI/Theme");document=gameObject.AddComponent<UIDocument>();document.panelSettings=settings;Root=document.rootVisualElement;Root.AddToClassList("screen");Root.styleSheets.Add(Resources.Load<StyleSheet>("UI/Playground"));Root.pickingMode=PickingMode.Ignore;BuildHUD();BuildPause();BuildResults();research=Box(Root,"research-layer");a.Research.Build(research);Visible(research,false);a.Setup.Build(Box(Root,"setup-layer"));SetQuality(PlayerPrefs.GetInt("presentation_quality",0));Refresh();if(!Application.isBatchMode&&System.Array.IndexOf(System.Environment.GetCommandLineArgs(),"--pg-benchmark")<0)a.Setup.Show();}
 void BuildHUD(){
 hud=Box(Root,"hud");hud.pickingMode=PickingMode.Ignore;var top=Box(hud,"topbar");top.pickingMode=PickingMode.Ignore;
 var brand=Box(top,"brand");Text(brand,"IMPULSE","brand-title");Text(brand,"ROOFTOP DUELS","brand-subtitle");
 var scoring=Box(top,"score card");var line=Box(scoring,"row scoreline");leftTitle=Text(line,"YOU","cyan score-side");score=Text(line,"0 : 0","score-number");rightTitle=Text(line,"LAYA","orange score-side");round=Text(scoring,"ROUND 1","eyebrow centered");roundClock=Text(scoring,"","round-clock");
 var shortcuts=Box(top,"row hud-shortcuts");KeyHint(shortcuts,"H","Controls");KeyHint(shortcuts,"ESC","Pause");
 aiPanel=Box(hud,"ai card diagnostics");connection=Text(aiPanel,"","eyebrow cyan");decision=Text(aiPanel,"","decision");latency=Text(aiPanel,"","muted");secondAI=Text(aiPanel,"","muted");Visible(aiPanel,false);
 center=Box(hud,"announcement");banner=Text(center,"3","countdown");subline=Text(center,"WIN THE SPACE. STAY ON THE ROOF.","eyebrow centered");
 tutorialPanel=Box(hud,"tutorial card");Text(tutorialPanel,"ROOFTOP TRAINING / UNSCORED","eyebrow cyan");tutorialText=Text(tutorialPanel,"","tutorial-text");Visible(tutorialPanel,false);
 threat=Box(hud,"threat");threatText=Text(threat,"PUSH INCOMING","threat-text");Visible(threat,false);
 var bottom=Box(hud,"bottom");var lower=Box(bottom,"row lower");var status=Box(lower,"card player-status");Text(status,"YOUR LOADOUT","eyebrow loadout-kicker");held=Text(status,"HANDS FREE","status-title");
 var abilities=Box(status,"row ability-row");var evasion=Box(abilities,"ability");dodge=Text(evasion,"SHIFT / DODGE READY","muted");dodgeFill=Box(Box(evasion,"cooldown-track"),"cooldown-fill");var shove=Box(abilities,"ability");pushStatus=Text(shove,"F / PUSH","muted");pushFill=Box(Box(shove,"cooldown-track"),"cooldown-fill orange-fill");
 var hint=Box(lower,"hint");edge=Text(hint,"","edge");interaction=Text(hint,"F  PUSH","interaction");var quick=Box(lower,"quick");Text(quick,"TAB  Statistics   ·   F4  AI details","muted");Text(quick,"F2  Experiment lab","muted");controls=Text(bottom,"WASD / Arrows Move   •   F Push / throw   •   E Grab / drop   •   Shift Dodge   •   Space Jump   •   Auto aim","controls");Visible(controls,false);
 hit=Box(hud,"impact");hit.pickingMode=PickingMode.Ignore;crosshair=Box(hud,"crosshair");crosshair.pickingMode=PickingMode.Ignore;Text(crosshair,"+","reticle");
 }
 void BuildPause(){pause=Box(Root,"scrim");var card=Box(pause,"pause-card");var scroll=new ScrollView(ScrollViewMode.Vertical);card.Add(scroll);
 Text(scroll,"IMPULSE    /    TIME OUT","eyebrow cyan");Text(scroll,"Take a breather.","pause-title");Text(scroll,"The rooftop can wait.","muted pause-subtitle");
 var columns=Box(scroll,"row pause-columns");var actions=Box(columns,"pause-actions");Button(actions,"BACK TO THE ROOF    →",()=>Pause(false),"primary large");Button(actions,"Start a rematch",NewMatch,"large");Button(actions,"Choose matchup",()=>a.Setup.Show(),"large");Button(actions,"Learn to play",()=>a.Setup.StartTutorial(),"large");Button(actions,"Experiment lab   ↗",()=>a.Research.Show(),"quiet");
 var aside=Box(columns,"pause-aside");Text(aside,"MAKE YOUR NEXT MOVE COUNT","eyebrow");KeyHint(aside,"WASD / ↑↓←→","Move");KeyHint(aside,"SHIFT","Dodge in move direction");KeyHint(aside,"E","Grab / drop");KeyHint(aside,"F","Push / throw held object");KeyHint(aside,"SPACE","Jump");Text(aside,"Fixed camera. Automatic facing and aiming.","muted pause-tip");
 var quality=new DropdownField("Graphics",new System.Collections.Generic.List<string>{"Balanced · 60 FPS","High · 120 FPS"},PlayerPrefs.GetInt("presentation_quality",0));quality.RegisterValueChangedCallback(e=>SetQuality(quality.index));scroll.Add(quality);perf=Text(scroll,"","muted performance");var footer=Box(scroll,"row pause-footer");Text(footer,"ESC / RESUME","eyebrow");Button(footer,"Quit to desktop",()=>Application.Quit(),"quiet");Visible(pause,false);}
 static void KeyHint(VisualElement parent,string key,string label){var row=Box(parent,"row key-hint");Text(row,key,"keycap");Text(row,label,"muted");}
 void BuildResults(){results=Box(Root,"scrim");var frame=Box(results,"results-card");var card=new ScrollView(ScrollViewMode.Vertical);frame.Add(card);Text(card,"THE MATCH, IN NUMBERS","eyebrow cyan");var summary=Box(card,"row results-heading");resultTitle=Text(summary,"Match snapshot","section-title");resultScore=Text(summary,"0 — 0","results-score");var columns=Box(card,"row");var table=Box(columns,"stats-table");var headings=Box(table,"stat-row");Text(headings,"PERFORMANCE","stat-name eyebrow");leftStatsTitle=Text(headings,"YOU","stat-value cyan");rightStatsTitle=Text(headings,"LAYA","stat-value orange");string[] labels={"Round wins","Self ring-outs","Grabs / throws","Throw hit rate","Successful pushes","Dodges","Time near edge","Average edge distance","Opponent-caused ring-outs"};for(int i=0;i<labels.Length;i++){var row=Box(table,"stat-row");Text(row,labels[i],"stat-name");left[i]=Text(row,"0","stat-value cyan");right[i]=Text(row,"0","stat-value orange");}var distribution=Box(columns,"distribution");distributionTitle=Text(distribution,"AI CHOICES","eyebrow");distributionPlayer=new DropdownField(new System.Collections.Generic.List<string>{"Right player","Left player"},0);distributionPlayer.RegisterValueChangedCallback(_=>RefreshResults());distribution.Add(distributionPlayer);for(int i=0;i<10;i++){var row=Box(distribution,"action-row");Text(row,actionNames[i],"action-name");var track=Box(row,"bar-track");bars[i]=Box(track,"bar-fill");counts[i]=Text(row,"0","action-count");}
 resultInfo=Text(card,"","muted result-info");var footer=Box(card,"row result-footer");rematch=Button(footer,"Play again   →",NewMatch,"primary");Button(footer,"Change matchup",()=>a.Setup.Show());Button(footer,"Experiment lab / exports",()=>a.Research.Show());Text(footer,"Hold TAB during play to inspect","muted");Visible(results,false);}
 void NewMatch(){a.Research.Close(false);Pause(false);a.Match.NewMatch();Refresh();}
 public void Pause(bool value){if(!value&&Arena.Instance.Setup.Open)return;Paused=value;Time.timeScale=value?0:1;if(!a)a=Arena.Instance;if(a&&a.Human)a.Human.GetComponent<HumanInput>().Capture(!value&&a.Match.Phase!=RoundPhase.MatchOver);if(pause!=null)RefreshVisibility();}
 public void SetQuality(int index){index=Mathf.Clamp(index,0,1);PlayerPrefs.SetInt("presentation_quality",index);QualitySettings.vSyncCount=0;Application.targetFrameRate=index==0?60:120;if(UnityEngine.Rendering.GraphicsSettings.currentRenderPipeline is UniversalRenderPipelineAsset urp){urp.renderScale=index==0?.85f:1;urp.msaaSampleCount=index==0?2:4;}}
 void Update(){if(Root==null)return;if(!a.Setup.Open&&!a.Research.Open){if(Keyboard.current?.f4Key.wasPressedThisFrame??false)diagnostics=!diagnostics;if(Keyboard.current?.hKey.wasPressedThisFrame??false)help=!help;}Visible(aiPanel,!a.Tutorial.Running&&(diagnostics||a.Client.Blocked||a.Client.LastRequestFailed||(a.Spectating&&a.LeftClient.LastRequestFailed)));Visible(controls,help);smoothFrame=Mathf.Lerp(smoothFrame,Time.unscaledDeltaTime,.06f);bool over=a.Match.Phase==RoundPhase.MatchOver;if(over&&!wasOver){a.Human.GetComponent<HumanInput>().Capture(false);Refresh();}wasOver=over;RefreshVisibility();Visible(hit,Time.unscaledTime<HitUntil&&!Paused);if(!Paused&&Time.unscaledTime>=nextRefresh){nextRefresh=Time.unscaledTime+.1f;Refresh();}if(Paused&&Time.unscaledTime>=nextRefresh){nextRefresh=Time.unscaledTime+.5f;Set(perf,$"{1/Mathf.Max(.001f,smoothFrame):0} FPS   ·   {smoothFrame*1000:0.0} ms / frame");}UpdateAim();UpdateCombat();}
 void RefreshVisibility(){bool setup=a.Setup.Open;bool lab=a.Research.Open;bool stats=!setup&&!lab&&!Paused&&((Keyboard.current?.tabKey.isPressed??false)||a.Match.Phase==RoundPhase.MatchOver);if(stats&&!statsVisible)RefreshResults();statsVisible=stats;Visible(research,lab);Visible(pause,Paused&&!lab&&!setup);Visible(results,stats);Visible(hud,!lab&&!setup);}
 void Refresh(){RefreshCount++;Set(score,$"{a.Match.HumanWins}  :  {a.Match.AIWins}");Set(round,$"ROUND {a.Match.Round:00}   /   {a.LayoutName.ToUpperInvariant()}   /   FIRST TO {a.Match.WinsRequired}");Set(roundClock,a.Tutorial.Running?"TRAINING":a.Match.SuddenDeath?"SUDDEN DEATH":a.Match.TimedRounds?$"{Mathf.FloorToInt(a.Match.RoundRemaining/60):00}:{Mathf.FloorToInt(a.Match.RoundRemaining%60):00}":"NO TIME LIMIT");roundClock.EnableInClassList("urgent",a.Match.SuddenDeath);Set(leftTitle,a.Spectating?"LAYA":"YOU");Set(rightTitle,a.RightName.ToUpperInvariant());bool offline=a.Client.LastRequestFailed;Set(connection,"●  "+(a.Client.Provider==AIProvider.Laya?"LAYA / "+a.Client.Backend:"TYPESAFE / "+a.Client.Model));connection.EnableInClassList("orange",offline||!a.Experiments.Ready);Set(decision,!a.Experiments.Ready?"Open F2 to review settings":a.Client.WaitStatus);Set(latency,a.Telemetry.RecordingError!=null?"Recording error · check storage":$"Last {a.Client.LastLatency:0} ms · {a.Telemetry.StatsFor(a.RightName).executed_decisions} played · {a.Telemetry.StatsFor(a.RightName).stale_responses} outdated");Visible(secondAI,a.Spectating);Set(secondAI,a.Spectating?$"LAYA / {a.LeftClient.Backend} · {a.LeftClient.WaitStatus}\nLast {a.LeftClient.LastLatency:0} ms · {a.Telemetry.StatsFor(a.LeftName).executed_decisions} played · {a.Telemetry.StatsFor(a.LeftName).stale_responses} outdated":"");Set(controls,a.Spectating?"SPECTATOR   /   Fixed arena view     ESC  Pause / matchup     TAB  Statistics     F2  Experiment lab":"WASD / ARROWS  Move     F  Push / throw     E  Grab / drop     SHIFT  Dodge     SPACE  Jump     AUTO AIM");Set(held,a.Spectating?"SPECTATING / LAYA":a.Human.Held?a.Human.Held.Kind.ToUpperInvariant()+" / "+(a.Human.Held.Kind=="barrel"?"HEAVY":a.Human.Held.Kind=="chair"?"LIGHT":"BALANCED"):"HANDS FREE");Set(dodge,a.Spectating?"INDEPENDENT MODELS":Time.time<a.Human.StunnedUntil?"Recovering balance…":Time.time<a.Human.NextDodge?$"Dodge in {a.Human.NextDodge-Time.time:0.0}s":"SHIFT / DODGE");var nearest=a.Human.Held?null:a.Human.Nearest();Set(interaction,a.Spectating?"FIXED ARENA VIEW":a.Human.Held?"F   THROW "+a.Human.Held.Kind.ToUpperInvariant():nearest?"E   GRAB "+nearest.Kind.ToUpperInvariant():"F   PUSH");Set(edge,a.Match.SuddenDeath?"STAY INSIDE THE ORANGE BOUNDARY":a.Human.Edge<1.8f?"OPEN EDGE · MOVE INWARD":"");bool countdown=a.Match.Phase==RoundPhase.Countdown;Visible(center,(countdown||a.Match.Phase==RoundPhase.Winner||a.Match.Practice)&&!a.Tutorial.Running);Set(banner,a.Match.Practice?"EXECUTOR LAB":countdown?Mathf.CeilToInt(a.Match.PhaseEnds-Time.time).ToString():a.Match.Announcement);banner.EnableInClassList("round-message",!countdown);Set(subline,a.Match.Practice?"PRACTICE / SCORING DISABLED":countdown?(a.Spectating?"LAYA VS TYPESAFE · SAME RULES":"SEND "+a.RightName.ToUpperInvariant()+" OFF. STAY ON THE ROOF."):"NEXT ROUND IN A MOMENT");if(statsVisible)RefreshResults();}
 void RefreshResults(){Set(resultScore,$"{a.Match.HumanWins} — {a.Match.AIWins}");Set(leftStatsTitle,a.Spectating?"LAYA":"YOU");Set(rightStatsTitle,a.RightName.ToUpperInvariant());Visible(distributionPlayer,a.Spectating);string actor=a.Spectating&&distributionPlayer.index==1?a.LeftName:a.RightName;Set(distributionTitle,actor.ToUpperInvariant()+" CHOICES");var aiStats=a.Telemetry.StatsFor(actor);var distribution=aiStats.action_counts;var h=a.Human;var l=a.AI;Set(resultTitle,a.Match.Phase==RoundPhase.MatchOver?a.Match.Announcement:"Match snapshot");string[] lv={a.Match.HumanWins.ToString(),a.Match.HumanSelfOuts.ToString(),$"{h.Grabs} / {h.Throws}",h.Throws>0?$"{100f*h.Hits/h.Throws:0}%":"—",h.Pushes.ToString(),h.Dodges.ToString(),$"{h.EdgeTime:0.0}s",$"{h.EdgeSum/Mathf.Max(.01f,h.Samples):0.0} m",a.Match.HumanEnvironmentalKOs.ToString()};string[] rv={a.Match.AIWins.ToString(),a.Match.AISelfOuts.ToString(),$"{l.Grabs} / {l.Throws}",l.Throws>0?$"{100f*l.Hits/l.Throws:0}%":"—",l.Pushes.ToString(),l.Dodges.ToString(),$"{l.EdgeTime:0.0}s",$"{l.EdgeSum/Mathf.Max(.01f,l.Samples):0.0} m",a.Match.AIEnvironmentalKOs.ToString()};for(int i=0;i<9;i++){Set(left[i],lv[i]);Set(right[i],rv[i]);}int max=1;foreach(int n in distribution)max=Mathf.Max(max,n);for(int i=0;i<10;i++){Set(counts[i],distribution[i].ToString());bars[i].style.width=Length.Percent(100f*distribution[i]/max);}Set(resultInfo,$"{actor}: {aiStats.executed_decisions} executed decisions   ·   {aiStats.total_latency_ms/Mathf.Max(1,aiStats.executed_decisions):0} ms mean model latency   ·   F3 exports full decision details");Visible(rematch,a.Match.Phase==RoundPhase.MatchOver);}
 void UpdateAim(){bool show=a.Guide&&a.Guide.HasAim&&!Paused;Visible(crosshair,show);if(!show)return;var screen=sceneCamera.WorldToScreenPoint(a.Guide.AimPoint);Visible(crosshair,screen.z>0);crosshair.style.left=screen.x/Screen.width*Root.resolvedStyle.width-10;crosshair.style.top=(1-screen.y/Screen.height)*Root.resolvedStyle.height-10;}
 void UpdateCombat(){var f=a.Human;Visible(tutorialPanel,a.Tutorial.Running);if(a.Tutorial.Running)Set(tutorialText,a.Tutorial.Instruction);
  dodgeFill.style.width=Length.Percent(100*Mathf.Clamp01(1-(f.NextDodge-Time.time)/1.1f));pushFill.style.width=Length.Percent(100*Mathf.Clamp01(1-(f.NextPush-Time.time)/.78f));
  Set(pushStatus,f.WindingUp?f.Attack.ToUpperInvariant()+" / COMMITTED":Time.time<f.RecoveryUntil?"RECOVERING":Time.time<f.NextPush?$"F / PUSH IN {f.NextPush-Time.time:0.0}s":"F / PUSH");
  bool show=!Paused&&!a.Setup.Open&&!a.Spectating&&a.AI.WindingUp;Visible(threat,show);if(show){Set(threatText,a.AI.Attack=="push"?"PUSH INCOMING":"THROW INCOMING");var screen=sceneCamera.WorldToScreenPoint(a.AI.transform.position+Vector3.up*2.3f);Visible(threat,screen.z>0);threat.style.left=Mathf.Clamp(screen.x/Screen.width*Root.resolvedStyle.width-80,12,Root.resolvedStyle.width-180);threat.style.top=Mathf.Clamp((1-screen.y/Screen.height)*Root.resolvedStyle.height,110,Root.resolvedStyle.height-100);}
 }
 void OnApplicationFocus(bool focus){if(!focus&&a&&System.Array.IndexOf(System.Environment.GetCommandLineArgs(),"--pg-benchmark")<0)Pause(true);}
 void OnDestroy(){Time.timeScale=1;if(settings)Destroy(settings);}
}
}
