using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;
using static Playground.UIFactory;
namespace Playground {
public enum MatchMode { HumanVsLaya, HumanVsTypeSafe, LayaVsTypeSafe }
// Credentials live only in this session. This component never serializes or logs them.
public class MatchSetup:MonoBehaviour {
 public MatchMode Mode{get;private set;}public bool Open{get;private set;}public bool Started{get;private set;}
 public string TypeSafeModel{get;private set;}="jev-latest";
 VisualElement root,cloud;DropdownField matchup,models;TextField key;Label message,versus,explanation;Button start,check,back;bool checking;int validationGeneration;string verifiedKey,sessionKey;string[] verifiedModels;
 static readonly List<string> Modes=new(){"Human vs Laya","Human vs TypeSafe","Laya vs TypeSafe"};
 public void Build(VisualElement parent){root=parent;root.AddToClassList("scrim");var card=Box(root,"setup-card");var scroll=new ScrollView(ScrollViewMode.Vertical);card.Add(scroll);var brand=Box(scroll,"row");var icon=new Image{image=Resources.Load<Texture2D>("UI/AppIcon")};icon.AddToClassList("setup-icon");brand.Add(icon);var title=Box(brand);Text(title,"PHYSICS PLAYGROUND","eyebrow cyan");Text(title,"Choose your matchup","setup-title");Text(scroll,"One rooftop. Same rules. Different minds.","description");
 matchup=new DropdownField("Matchup",Modes,0){name="matchup"};scroll.Add(matchup);matchup.RegisterValueChangedCallback(_=>Refresh());var pairing=Box(scroll,"setup-pairing");versus=Text(pairing,"","setup-versus");explanation=Text(pairing,"","description");
 cloud=Box(scroll,"setup-cloud");Text(cloud,"TYPESAFE / JEV","eyebrow orange");key=new TextField("API key"){isPasswordField=true,name="typesafe-key"};cloud.Add(key);key.RegisterValueChangedCallback(_=>{validationGeneration++;verifiedKey=null;verifiedModels=null;Refresh();});Text(cloud,"Kept only for this session. You can also launch with TYPESAFE_API_KEY set.","muted");
 models=new DropdownField("Model",new List<string>{"jev-latest"},0){name="typesafe-model"};cloud.Add(models);models.RegisterValueChangedCallback(_=>Refresh());check=Button(cloud,"Check key & load models",()=>StartCoroutine(CheckKey()),"large");check.name="check-typesafe";Button(cloud,"Get an API key ↗",()=>Application.OpenURL("https://console.typesafe.ai"),"quiet");Text(cloud,"TypeSafe receives arena observations and your action instructions over HTTPS. Cloud requests use your API account. Gameplay requests start only when you enter the arena.","muted");
 message=Text(scroll,"","setup-message");start=Button(scroll,"Enter the arena   →",StartSelected,"primary large");start.name="start-match";back=Button(scroll,"Back to current match",Close,"quiet");Button(scroll,"Quit to desktop",()=>Application.Quit(),"quiet");Visible(root,false);
 }
 public void Show(){if(root==null)return;var a=Arena.Instance;a.Research.Close(false);a.GetComponent<ExecutorDebugPanel>().Open=false;a.Match.Practice=false;Open=true;a.HUD.Pause(true);a.Match.Generation++;a.Client.CancelPending();a.LeftClient.CancelPending();a.StopExecutors("match_setup");matchup.SetValueWithoutNotify(Modes[(int)Mode]);key.SetValueWithoutNotify(sessionKey??Environment.GetEnvironmentVariable("TYPESAFE_API_KEY")??"");Visible(root,true);Refresh();}
 void Refresh(){if(start==null)return;bool remote=matchup.index!=0;Visible(cloud,remote);Visible(back,Started);Set(versus,matchup.index==2?"LAYA    ×    TYPESAFE":matchup.index==1?"YOU    ×    TYPESAFE":"YOU    ×    LAYA");Set(explanation,matchup.index==2?"Watch two independent AI players compete. Cyan is local Laya; orange is TypeSafe. Drag with the right mouse button to orbit.":matchup.index==1?"Take the cyan corner against TypeSafe's cloud model.":"Take the cyan corner against Laya, running locally on this Mac.");bool verified=verifiedKey==key.value&&verifiedModels!=null&&Array.IndexOf(verifiedModels,models.value)>=0;start.SetEnabled(!checking&&(!remote||verified));check.SetEnabled(!checking&&!string.IsNullOrWhiteSpace(key.value));Set(message,!remote?"Local Laya uses 127.0.0.1:8000. The launcher starts it for you.":checking?"Checking TypeSafe access…":verified?"Connected · "+models.value+" · ready to play":"Enter a key and check access before starting.");}
 IEnumerator CheckKey(){checking=true;verifiedKey=null;verifiedModels=null;int version=validationGeneration;string submitted=key.value.Trim();Refresh();yield return LayaClient.DiscoverModels(submitted,(names,error)=>{if(version!=validationGeneration)return;if(error!=null){Set(message,error);return;}verifiedKey=submitted;key.SetValueWithoutNotify(submitted);verifiedModels=names;models.choices=new List<string>(names);models.SetValueWithoutNotify(Array.IndexOf(names,TypeSafeModel)>=0?TypeSafeModel:names[0]);});checking=false;if(version==validationGeneration&&verifiedModels!=null)Refresh();else{start.SetEnabled(matchup.index==0);check.SetEnabled(!string.IsNullOrWhiteSpace(key.value));}}
 void StartSelected(){var mode=(MatchMode)matchup.index;if(mode!=MatchMode.HumanVsLaya&&(verifiedKey!=key.value||verifiedModels==null||Array.IndexOf(verifiedModels,models.value)<0))return;if(!Configure(mode,models.value,key.value))return;Started=true;Open=false;Visible(root,false);Arena.Instance.Match.NewMatch();Arena.Instance.HUD.Pause(false);key.SetValueWithoutNotify("");}
 public bool Configure(MatchMode mode,string model="jev-latest",string credential=null){if(!Enum.IsDefined(typeof(MatchMode),mode)||mode!=MatchMode.HumanVsLaya&&(string.IsNullOrWhiteSpace(credential)||string.IsNullOrWhiteSpace(model)))return false;var a=Arena.Instance;a.Match.Generation++;a.StopExecutors("matchup_changed");a.Client.CancelPending();a.LeftClient.CancelPending();Mode=mode;TypeSafeModel=model;sessionKey=credential;a.Human.Actor=a.LeftName;a.AI.Actor=a.RightName;a.Human.name=a.LeftName;a.AI.name=a.RightName;a.LeftClient.Configure(AIProvider.Laya);a.Client.Configure(mode==MatchMode.HumanVsLaya?AIProvider.Laya:AIProvider.TypeSafe,model,credential);a.LeftBrain.Enabled=mode==MatchMode.LayaVsTypeSafe;a.Brain.Enabled=true;return true;}
 public void Close(){if(!Started)return;validationGeneration++;Open=false;Visible(root,false);key.SetValueWithoutNotify("");Arena.Instance.HUD.Pause(false);}
}
}
