using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UIElements;
using static Playground.UIFactory;
namespace Playground {
public class ResearchPanel:MonoBehaviour {
 public string LastExportPath,ExportError;public bool Open;public bool Exporting{get;private set;}public int BuildCount{get;private set;}
 ExperimentProfile draft;string selectedLog;VisualElement root,body;Label message;Button exportButton;int activeTab;
 readonly System.Collections.Generic.List<VisualElement> pages=new();readonly System.Collections.Generic.List<Button> tabs=new();
 public void Build(VisualElement host){root=host;Rebuild();}
 public void Show(){var a=Arena.Instance;var debug=a.GetComponent<ExecutorDebugPanel>();if(debug.Open){debug.Open=false;a.Match.Practice=false;a.Match.NewMatch();}draft=a.Experiments.Ready?a.Experiments.Current:a.Experiments.Defaults();selectedLog=a.Telemetry.FilePath;Open=true;a.HUD.Pause(true);Rebuild();Status(a.Experiments.Error??"Changes apply to a new match. Your current recording keeps its original settings.");}
 public void Close(bool resume=true){Open=false;if(resume)Arena.Instance.HUD.Pause(false);}
 void Update(){var k=Keyboard.current;if(k==null)return;if(k.f2Key.wasPressedThisFrame){if(Open)Close();else Show();}if(k.f3Key.wasPressedThisFrame){if(!Open)Show();BeginExport();}}
 void Status(string text){if(message!=null)message.text=text;}
 void Rebuild(){if(root==null)return;BuildCount++;root.Clear();pages.Clear();tabs.Clear();var a=Arena.Instance;if(draft==null)draft=a.Experiments.Ready?a.Experiments.Current:a.Experiments.Defaults();var header=Box(root,"row lab-header");var titles=Box(header);Text(titles,"PHYSICS PLAYGROUND / RESEARCH","eyebrow cyan");Text(titles,"Experiment lab","lab-title");var headActions=Box(header,"row");Text(headActions,"SIMULATION PAUSED","eyebrow");Button(headActions,"Back to game   Esc",()=>Close(),"quiet");var tabbar=Box(root,"lab-tabs");body=Box(root,"lab-body");string[] names={"01  Setup","02  Actions","03  Observations","04  Recordings"};for(int i=0;i<4;i++){int index=i;tabs.Add(Button(tabbar,names[i],()=>SelectTab(index)));var scroll=new ScrollView(ScrollViewMode.Vertical);scroll.AddToClassList("lab-page");body.Add(scroll);pages.Add(scroll);}
 BuildSetup(pages[0]);BuildActions(pages[1]);BuildObservations(pages[2]);BuildRecordings(pages[3]);var footer=Box(root,"lab-footer");message=Text(footer,"Changes apply to a new match. Recordings keep their original settings.","lab-message");var buttons=Box(footer,"row footer-buttons");var left=Box(buttons,"row");Button(left,"Apply & start new match   →",()=>Apply(),"primary");Button(left,"Restore defaults",()=>{draft=a.Experiments.Defaults();Rebuild();Status("Defaults loaded into the draft. Apply to start a match.");});Button(buttons,"Reload saved profile",Reload,"quiet");SelectTab(activeTab);}
 void BuildSetup(VisualElement page){var columns=Box(page,"lab-columns");var identity=Box(columns,"lab-column");Text(identity,"Name this experiment","lab-section");Text(identity,"Group runs under an experiment ID. Use a condition ID for each variation you want to compare.","description");Field(identity,"Experiment",draft.experiment_id,x=>draft.experiment_id=x);Field(identity,"Condition",draft.condition_id,x=>draft.condition_id=x);Field(identity,"Notes",draft.notes,x=>draft.notes=x,true);Text(identity,"IDs: letters, numbers, dots, underscores and hyphens.","muted");var config=Box(columns,"lab-column");Text(config,"Decision timing","lab-section");Text(config,"Set the maximum number of request starts per game second. Model latency and committed actions may make actual decisions slower.","description");var hz=new FloatField("Requests / sec"){value=draft.max_decisions_per_second};hz.RegisterValueChangedCallback(e=>draft.max_decisions_per_second=e.newValue);config.Add(hz);Text(config,"Allowed range: 0.25–10. Pausing stops game time.","muted");Text(config,"Model instructions","lab-section");Field(config,"",draft.questions.action.instructions,x=>draft.questions.action.instructions=x,true);Text(config,"Laya chooses every tactical action. Service failures cause a neutral wait and retry.","description");Button(config,"Open profile JSON",EditFile,"quiet");}
 void BuildActions(VisualElement page){var columns=Box(page,"lab-columns");var choices=Box(columns,"lab-column");Text(choices,"What can Laya choose?","lab-section");Text(choices,"Choose a subset of the ten supported actions. Range, cooldown and held-object rules still apply.","description");foreach(string action in Enum.GetNames(typeof(SemanticAction))){var toggle=new Toggle{text=action.Replace('_',' '),value=draft.actions.Contains(action)};toggle.RegisterValueChangedCallback(e=>draft.actions=e.newValue?draft.actions.Concat(new[]{action}).ToArray():draft.actions.Where(x=>x!=action).ToArray());choices.Add(toggle);}var explain=Box(columns,"lab-column");Text(explain,"Execution stays fair","lab-section");Text(explain,"Human and Laya share the same movement, mass, jump, grab range and impact response.\n\nIf none of the selected actions are physically possible, Laya waits. No substitute policy chooses for it.\n\nEdit the per-action descriptions in the profile JSON, then reload your draft here.","description");Button(explain,"Open profile JSON",EditFile);}
 void BuildObservations(VisualElement page){Text(page,"What can Laya observe?","lab-section");Text(page,"Only checked fields are sent to the model. Full diagnostic state is still retained in the recording for analysis.","description");var grid=Box(page,"schema-grid");foreach(string group in new[]{"self.","opponent.","nearest_object.","other"}){var column=Box(grid,"lab-column schema-group");Text(column,group=="other"?"Context":group.TrimEnd('.').Replace('_',' '),"lab-section");foreach(string path in StateSchema.Paths.Where(x=>group=="other"?!x.Contains("."):x.StartsWith(group,StringComparison.Ordinal))){var toggle=new Toggle{text=path.Substring(path.IndexOf('.')+1).Replace('_',' '),value=draft.state_fields.Contains(path)};toggle.RegisterValueChangedCallback(e=>draft.state_fields=e.newValue?draft.state_fields.Concat(new[]{path}).ToArray():draft.state_fields.Where(x=>x!=path).ToArray());column.Add(toggle);}}Text(page,"Mechanical eligibility can disclose constraints even when related observations are omitted. Account for this in ablation experiments.","description");}
 void BuildRecordings(VisualElement page){var columns=Box(page,"lab-columns");var list=Box(columns,"lab-column log-list");Text(list,"Recent matches","lab-section");var paths=Directory.GetFiles(Arena.Instance.Telemetry.DirectoryPath,"*.jsonl").OrderByDescending(x=>x).Take(12);foreach(var path in paths){var captured=path;var button=Button(list,Path.GetFileNameWithoutExtension(path)+(path==Arena.Instance.Telemetry.FilePath?"  · current":""),()=>{selectedLog=captured;foreach(var b in list.Query<Button>().ToList())b.EnableInClassList("selected",b.userData as string==selectedLog);});button.userData=path;button.EnableInClassList("selected",path==selectedLog);}
 var detail=Box(columns,"lab-column");Text(detail,"Replay. Inspect. Compare.","lab-section");Text(detail,"Export an offline report with a spatial timeline, exact model inputs, decisions and outcomes. JSON and CSV data are included.\n\nThe replay samples positions at up to 10 Hz. It is a visual record, not a deterministic physics resimulation.","description");exportButton=Button(detail,Exporting?"Exporting…":"Export & open inspector   →",()=>BeginExport(),"primary");exportButton.SetEnabled(!Exporting);Button(detail,"Open recordings folder",()=>Application.OpenURL(new Uri(Arena.Instance.Telemetry.DirectoryPath+Path.DirectorySeparatorChar).AbsoluteUri));Text(detail,"Exports run in the background. You can continue using the menus while a report is prepared.","muted");}
 static TextField Field(VisualElement parent,string name,string value,Action<string> changed,bool multiline=false){var f=new TextField(name){value=value??"",multiline=multiline};if(multiline)f.AddToClassList("multiline");f.RegisterValueChangedCallback(e=>changed(e.newValue));parent.Add(f);return f;}
 public void SelectTab(int index){activeTab=Mathf.Clamp(index,0,3);for(int i=0;i<pages.Count;i++){Visible(pages[i],i==activeTab);tabs[i].EnableInClassList("selected",i==activeTab);}}
 public bool Apply(){var error=draft.Validate();if(error!=null){Status(error);return false;}if(!Arena.Instance.Experiments.Apply(draft)){Status(Arena.Instance.Experiments.Error);return false;}Arena.Instance.Match.Practice=false;Arena.Instance.Match.NewMatch();Close();return true;}
 void Reload(){try{var loaded=JsonUtility.FromJson<ExperimentProfile>(File.ReadAllText(Arena.Instance.Experiments.ProfilePath));var error=loaded?.Validate()??"Empty profile";if(loaded!=null&&loaded.Validate()==null){draft=loaded;Rebuild();Status("Saved profile loaded. Apply to start a new match.");}else Status(error);}catch(Exception e){Status(e.Message);}}
 void EditFile(){try{var path=Arena.Instance.Experiments.ProfilePath;if(!File.Exists(path))File.WriteAllText(path,JsonUtility.ToJson(draft,true));Application.OpenURL(new Uri(path).AbsoluteUri);}catch(Exception e){Status(e.Message);}}
 public async void BeginExport(bool openBrowser=true){if(Exporting)return;Exporting=true;ExportError=null;exportButton?.SetEnabled(false);Status("Preparing your report… menus remain available.");try{var telemetry=Arena.Instance.Telemetry;string source=selectedLog??telemetry.FilePath;var snapshot=await telemetry.SnapshotAsync(source);string template=Path.Combine(Application.streamingAssetsPath,"inspector-template.html");string path=await Task.Run(()=>MatchExport.Export(source,template,snapshot));if(!this)return;LastExportPath=path;Status("Export complete: "+Path.GetDirectoryName(path));if(openBrowser)Application.OpenURL(new Uri(path).AbsoluteUri);}catch(Exception e){ExportError=e.Message;if(this)Status("Export failed: "+e.Message);}finally{Exporting=false;if(this){exportButton?.SetEnabled(true);}}}
 // Synchronous entry point retained for automated tests and batch tooling only.
 public string Export(bool openBrowser=true){Arena.Instance.Telemetry.Flush();string path=MatchExport.Export(selectedLog??Arena.Instance.Telemetry.FilePath);if(openBrowser)Application.OpenURL(new Uri(path).AbsoluteUri);return path;}
}
}
