using System;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEngine.InputSystem;
namespace Playground {
public class ResearchPanel:MonoBehaviour {
 public bool Open;ExperimentProfile draft;Vector2 scroll;string message="",selectedLog;string[] logs=Array.Empty<string>();GUIStyle title,label,button;
 public void Show(){var debug=Arena.Instance.GetComponent<ExecutorDebugPanel>();if(debug.Open){debug.Open=false;Arena.Instance.Match.Practice=false;Arena.Instance.Match.NewMatch();}Open=true;draft=Arena.Instance.Experiments.Ready?Arena.Instance.Experiments.Current:Arena.Instance.Experiments.Defaults();message=Arena.Instance.Experiments.Error??"Changes apply to a new match. Existing logs retain their original profile.";Refresh();Arena.Instance.HUD.Pause(true);}
 void Refresh(){logs=Directory.GetFiles(Arena.Instance.Telemetry.DirectoryPath,"*.jsonl").OrderByDescending(x=>x).Take(12).ToArray();selectedLog=Arena.Instance.Telemetry.FilePath;}
 public void Close(){Open=false;Arena.Instance.HUD.Pause(false);}
 void Update(){var k=Keyboard.current;if(k==null)return;if(k.f2Key.wasPressedThisFrame){if(Open)Close();else Show();}if(k.f3Key.wasPressedThisFrame){if(!Open)Show();Export();}}
 public string Export(bool openBrowser=true){try{string path=MatchExport.Export(selectedLog??Arena.Instance.Telemetry.FilePath);message="Exported JSON, JSONL, CSV and report: "+Path.GetDirectoryName(path);if(openBrowser)Application.OpenURL(new Uri(path).AbsoluteUri);return path;}catch(Exception e){message="Export failed: "+e.Message;return null;}}
 void OnGUI(){if(!Open)return;GUI.depth=-100;GUI.matrix=Matrix4x4.TRS(Vector3.zero,Quaternion.identity,new Vector3(Screen.width/1440f,Screen.height/900f,1));if(title==null){title=new GUIStyle(GUI.skin.label){fontSize=27,fontStyle=FontStyle.Bold};label=new GUIStyle(GUI.skin.label){fontSize=16,wordWrap=true};button=new GUIStyle(GUI.skin.button){fontSize=16};}
 GUI.color=new Color(.035f,.065f,.09f,.98f);GUI.DrawTexture(new Rect(35,25,1370,850),Texture2D.whiteTexture);GUI.color=Color.white;GUI.Box(new Rect(35,25,1370,850),GUIContent.none);GUILayout.BeginArea(new Rect(65,45,1310,810));GUILayout.Label("EXPERIMENT LAB   /   F2",title);GUILayout.Label("Local Laya chooses every action. Simulation is paused while you configure or inspect.",label);
 scroll=GUILayout.BeginScrollView(scroll);GUILayout.BeginHorizontal();GUILayout.Label("Experiment ID",GUILayout.Width(120));draft.experiment_id=GUILayout.TextField(draft.experiment_id,GUILayout.Width(230));GUILayout.Label("Condition ID",GUILayout.Width(120));draft.condition_id=GUILayout.TextField(draft.condition_id,GUILayout.Width(230));GUILayout.Label("Request cap / game second",GUILayout.Width(210));draft.max_decisions_per_second=GUILayout.HorizontalSlider(draft.max_decisions_per_second,.25f,10,GUILayout.Width(180));GUILayout.Label(draft.max_decisions_per_second.ToString("0.00"));GUILayout.EndHorizontal();
 GUILayout.Label("This is a maximum request-start rate. Model latency and committed actions can make actual decisions slower.",label);
 GUILayout.BeginHorizontal();GUILayout.Label("Notes",GUILayout.Width(120));draft.notes=GUILayout.TextField(draft.notes??"");GUILayout.EndHorizontal();
 GUILayout.Space(10);GUILayout.BeginHorizontal();GUILayout.BeginVertical(GUILayout.Width(470));GUILayout.Label("ACTION SCHEMA",label);foreach(var action in Enum.GetNames(typeof(SemanticAction))){bool was=draft.actions.Contains(action),now=GUILayout.Toggle(was,action);if(now!=was)draft.actions=now?draft.actions.Concat(new[]{action}).ToArray():draft.actions.Where(x=>x!=action).ToArray();}GUILayout.Label("Impossible actions remain excluded. If none are legal, Laya waits. No fallback policy.",label);GUILayout.Space(12);GUILayout.Label("Question instructions",label);draft.questions.action.instructions=GUILayout.TextArea(draft.questions.action.instructions,GUILayout.Height(95));GUILayout.Label("Individual action criteria can be edited in profile.json, then reloaded here.",label);GUILayout.EndVertical();
 GUILayout.BeginVertical(GUILayout.Width(420));GUILayout.Label("OBSERVATION SCHEMA",label);foreach(var path in StateSchema.Paths){bool was=draft.state_fields.Contains(path),now=GUILayout.Toggle(was,path);if(now!=was)draft.state_fields=now?draft.state_fields.Concat(new[]{path}).ToArray():draft.state_fields.Where(x=>x!=path).ToArray();}GUILayout.EndVertical();
 GUILayout.BeginVertical();GUILayout.Label("INSPECT SAVED MATCH",label);foreach(var log in logs)if(GUILayout.Toggle(selectedLog==log,Path.GetFileNameWithoutExtension(log),GUI.skin.button))selectedLog=log;GUILayout.Space(12);if(GUILayout.Button("Export & open inspector  /  F3",button))Export();if(GUILayout.Button("Open telemetry folder",button))Application.OpenURL(new Uri(Arena.Instance.Telemetry.DirectoryPath+Path.DirectorySeparatorChar).AbsoluteUri);GUILayout.Label("Replay uses sampled positions at 10 Hz. Full state, exact request inputs and raw responses are retained in JSONL.",label);GUILayout.EndVertical();GUILayout.EndHorizontal();GUILayout.EndScrollView();
 GUILayout.Label(message,label);GUILayout.BeginHorizontal();if(GUILayout.Button("Apply & start new match",button,GUILayout.Height(42))){var error=draft.Validate();if(error!=null)message=error;else if(Arena.Instance.Experiments.Apply(draft)){Arena.Instance.Match.Practice=false;Arena.Instance.Match.NewMatch();Close();}else message=Arena.Instance.Experiments.Error;}
 if(GUILayout.Button("Reload profile.json",button)){try{var p=JsonUtility.FromJson<ExperimentProfile>(File.ReadAllText(Arena.Instance.Experiments.ProfilePath));var error=p.Validate();if(error==null){draft=p;message="Loaded saved profile. Apply to start a match.";}else message=error;}catch(Exception e){message=e.Message;}}
 if(GUILayout.Button("Edit profile file",button)){if(!File.Exists(Arena.Instance.Experiments.ProfilePath))File.WriteAllText(Arena.Instance.Experiments.ProfilePath,JsonUtility.ToJson(draft,true));Application.OpenURL(new Uri(Arena.Instance.Experiments.ProfilePath).AbsoluteUri);}
 if(GUILayout.Button("Restore defaults",button))draft=Arena.Instance.Experiments.Defaults();if(GUILayout.Button("Resume  /  F2",button))Close();GUILayout.EndHorizontal();GUILayout.EndArea();
 }
}
}
