#if UNITY_EDITOR
using System;
using System.Collections;
using System.IO;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;
namespace Playground.Editor {
[InitializeOnLoad] public static class CombatValidationLauncher {
 static CombatValidationLauncher(){EditorApplication.playModeStateChanged+=state=>{if(state==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool("PG.Combat",false))new GameObject("Combat validation").AddComponent<CombatValidation>();};}
 public static void Run(){SessionState.SetBool("PG.Combat",true);UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/Rooftop.unity");foreach(var db in UnityEditor.Search.SearchService.EnumerateDatabases()){}EditorApplication.isPlaying=true;}
}
public class CombatValidation:MonoBehaviour {
 void Check(bool ok,string name){File.AppendAllText("validation/combat-upgrade.txt",(ok?"PASS ":"FAIL ")+name+"\n");if(!ok){Debug.LogError("COMBAT FAIL: "+name);EditorApplication.Exit(1);throw new Exception(name);}Debug.Log("COMBAT PASS: "+name);}
 IEnumerator Start(){File.WriteAllText("validation/combat-upgrade.txt","");yield return new WaitForSeconds(.7f);var a=Arena.Instance;var f=a.Human;var o=a.AI;a.Brain.Enabled=a.LeftBrain.Enabled=false;a.Client.CancelPending();a.LeftClient.CancelPending();a.StopExecutors("validation");a.Match.Practice=true;f.Active=o.Active=true;f.GetComponent<HumanInput>().enabled=false;
  o.ResetAt(new Vector3(0,.1f,1));yield return new WaitForFixedUpdate();yield return new WaitForFixedUpdate();Check(Vector3.Dot(o.transform.forward,Vector3.back)>.99f,"reset facing persists through rigidbody interpolation");
  a.ResetArena();f.ResetAt(new Vector3(0,.1f,0));o.ResetAt(new Vector3(0,.1f,1.2f));yield return new WaitForSeconds(.1f);
  Check(Array.IndexOf(ActionSchema.Available(a.Executor,a.Executor.ObserveContext()),"APPROACH_OPPONENT")<0,"already-arrived approach is excluded as a no-op");
  f.ResetAt(new Vector3(0,.1f,0));o.ResetAt(new Vector3(0,.1f,1.65f));f.SnapFace(Vector3.forward);yield return new WaitForSeconds(.1f);
  Check(f.Push(),"push accepted");Check(o.LastHitTime<0&&f.WindingUp,"push has anticipation before contact");yield return new WaitForSeconds(.26f);Check(f.LastPushHit&&o.LastAttacker==f,"push contacts opponent after wind-up");Check(!f.Dodge(Vector3.right),"attack recovery blocks dodge cancellation");
  a.ResetArena();f.ResetAt(new Vector3(0,.1f,0));o.ResetAt(new Vector3(0,.1f,1.65f));f.SnapFace(Vector3.forward);var wall=Arena.Shape("Test cover",PrimitiveType.Cube,new Vector3(0,1,.8f),new Vector3(1.5f,2,.12f),Arena.Material(Color.gray));yield return new WaitForSeconds(.1f);f.Push();yield return new WaitForSeconds(.26f);Check(o.LastAttacker==null&&!f.LastPushHit,"solid cover blocks push");Destroy(wall);yield return null;
  a.ResetArena();f.ResetAt(Vector3.up*.1f);o.ResetAt(new Vector3(0,.1f,1.65f));f.SnapFace(Vector3.forward);yield return new WaitForSeconds(.1f);f.Push();o.Dodge(Vector3.right);yield return new WaitForSeconds(.28f);Check(o.LastAttacker==null&&!f.LastPushHit,"side dodge evades telegraphed push");Check(f.RecoveryUntil-Time.time>.25f,"miss has punishable recovery");
  a.ResetArena();var prop=Arena.Props.Find(p=>p.Kind=="barrel");f.ResetAt(prop.transform.position+Vector3.back*1.5f-Vector3.up*.5f);yield return new WaitForSeconds(.1f);Check(f.Grab(prop),"heavy prop grab");Check(f.CarryMultiplier<.8f,"heavy carry slows movement");f.Knock(Vector3.zero,o);Check(!f.Release(true,Vector3.forward)&&!f.Jump()&&!f.Push()&&!f.Dodge(Vector3.right),"stun consistently blocks every combat action");yield return new WaitForSeconds(.32f);Check(f.Release(true,Vector3.forward),"throw begins after recovery");Check(prop.Body.isKinematic&&f.WindingUp,"heavy throw has wind-up");f.Knock(Vector3.zero,o);yield return new WaitForSeconds(.45f);Check(f.Held==prop&&prop.Body.isKinematic,"impact cancels pending throw");
  f.ResetAt(new Vector3(0,.1f,-3));a.ResetArena();prop=Arena.Props.Find(p=>p.Kind=="chair");f.ResetAt(prop.transform.position+Vector3.back*1.5f-Vector3.up*.4f);f.SnapFace(Vector3.forward);yield return new WaitForSeconds(.1f);Check(f.Grab(prop),"light prop grab");yield return new WaitForFixedUpdate();var expected=f.ThrowVelocity(Vector3.forward+Vector3.up*.3f);Vector3 actual=Vector3.zero;Action<string> capture=e=>{if(e=="throw"){actual=prop.Body.linearVelocity;expected=f.ThrowDirection(Vector3.forward+Vector3.up*.3f)*prop.ThrowSpeed+f.Body.linearVelocity*.4f;}};f.Event+=capture;f.Release(true,Vector3.forward+Vector3.up*.3f);yield return new WaitForSeconds(.16f);f.Event-=capture;Check(Vector3.Distance(expected,actual)<.15f,"preview and actual launch share velocity");Check(prop.ThrowSpeed>20,"light prop has faster throw");
  Check(Quaternion.Angle(a.CameraRig.transform.rotation,OrbitCamera.ViewRotation)<.01f,"arena camera keeps its fixed orientation");
  a.ResetArena();f.ResetAt(new Vector3(0,.1f,0));o.ResetAt(new Vector3(0,.1f,1.5f));f.SnapFace(Vector3.forward);f.Push();a.ResetArena();yield return new WaitForSeconds(.4f);Check(!f.WindingUp&&o.LastAttacker==null,"round reset cancels scheduled attacks");
  a.Match.Layout=1;a.ResetArena();Check(Mathf.Abs(Arena.Props[0].transform.position.z)<.1f,"Crossfire layout loads");a.Match.Layout=2;a.ResetArena();Check(Arena.Props[0].transform.position.x<-5,"Flank layout loads");a.Match.Layout=0;a.ResetArena();Check(Mathf.Abs(Arena.Props[0].transform.position.z+3)<.1f,"fixed baseline is reproducible");
  a.Match.Practice=false;a.Match.NewMatch();a.Match.TimedRounds=true;a.Match.Phase=RoundPhase.Fight;a.Match.FightStarted=Time.time-80;f.Active=o.Active=true;f.ResetAt(new Vector3(8,.1f,0));o.ResetAt(new Vector3(-8,.1f,0));Check(a.Match.SafeHalfExtent<7,"sudden death shrinks safe area");yield return new WaitForSeconds(1);Check(a.Match.Phase==RoundPhase.Winner&&a.Match.HumanWins==0&&a.Match.AIWins==0,"simultaneous sudden-death outs draw");a.Match.TimedRounds=false;
  a.Tutorial.Begin();Check(a.Tutorial.Running&&!a.Brain.Enabled&&a.Match.Practice,"tutorial is unscored with model disabled");prop=Arena.Props.Find(p=>p.Kind=="crate");f.ResetAt(new Vector3(0,.1f,-3));prop.Body.position=new Vector3(0,.8f,-2);prop.transform.position=prop.Body.position;f.SnapFace(Vector3.forward);yield return new WaitForSeconds(.1f);f.Grab(prop);Check(a.Tutorial.Stage==1,"tutorial advances on actual grab");yield return new WaitForSeconds(.1f);f.Release(true,Vector3.forward+Vector3.up*.1f);float deadline=Time.time+3;while(a.Tutorial.Stage==1&&Time.time<deadline)yield return null;Check(a.Tutorial.Stage==2,"tutorial advances on physical throw hit");deadline=Time.time+4;while(!o.WindingUp&&Time.time<deadline)yield return null;Check(o.WindingUp,"training opponent telegraphs an attack");f.Dodge(Vector3.right);deadline=Time.time+2;while(a.Tutorial.Stage==2&&Time.time<deadline)yield return null;Check(a.Tutorial.Stage==3,"tutorial verifies an evaded attack");f.ResetAt(new Vector3(0,.1f,6.4f));f.SnapFace(Vector3.forward);yield return new WaitForSeconds(.1f);f.Push();deadline=Time.time+3;while(a.Tutorial.Stage==3&&Time.time<deadline)yield return null;Check(a.Tutorial.Stage==4,"tutorial completes on a physical ring-out");a.Tutorial.Stop();Check(!a.Tutorial.Running&&!a.Match.Practice,"leaving tutorial restores normal match rules");
  // Game feel: hit-stop, edge slow motion, ground rings, pooled effects, audio, optional kick and AI intent.
  if(a.Tutorial.Running)a.Tutorial.Stop(false);a.Match.Practice=true;a.Match.Phase=RoundPhase.Fight;f.Active=o.Active=true;a.HUD.Pause(false);bool kickSetting=OrbitCamera.KickEnabled,intentSetting=GameHUD.IntentLabels;OrbitCamera.KickEnabled=false;
  a.ResetArena();f.ResetAt(new Vector3(0,.1f,0));o.ResetAt(new Vector3(0,.1f,1.65f));f.SnapFace(Vector3.forward);yield return new WaitForSeconds(.1f);f.Push();float until=Time.realtimeSinceStartup+1;while(o.LastAttacker!=f&&Time.realtimeSinceStartup<until)yield return null;
  Check(o.LastAttacker==f&&Time.timeScale<.1f&&a.Feedback.TimeEffectActive,"a landed hit triggers a brief hit-stop");yield return new WaitForSecondsRealtime(.2f);Check(Time.timeScale==1,"hit-stop hands back normal time");
  a.Feedback.HitStop(1);yield return null;a.HUD.Pause(true);yield return null;Check(Time.timeScale==0,"pause wins over hit-stop");a.HUD.Pause(false);yield return new WaitForSecondsRealtime(1.1f);Check(Time.timeScale==1,"time is normal after pausing during hit-stop");
  a.ResetArena();o.ResetAt(new Vector3(0,.1f,9.3f));until=Time.realtimeSinceStartup+4;while(!a.Feedback.TimeEffectActive&&Time.realtimeSinceStartup<until){o.Move=Vector3.forward;yield return null;}o.Move=Vector3.zero;
  Check(a.Feedback.TimeEffectActive&&Time.timeScale<=GameFeedback.FallSlowScale+.01f,"going over the edge triggers a slow-motion beat");yield return new WaitForSecondsRealtime(GameFeedback.FallSlowSeconds+.1f);Check(Time.timeScale==1,"slow motion ends on its own");
  a.ResetArena();f.ResetAt(new Vector3(2,.1f,-2));yield return new WaitForSeconds(.3f);var ring=a.Markers.RingFor(f);float groundRadius=ring.bounds.extents.x;
  Check(ring.enabled&&ring.GetPosition(0).y<.1f&&Vector2.Distance(new Vector2(ring.bounds.center.x,ring.bounds.center.z),new Vector2(2,-2))<.25f,"a ground ring sits on the roof under each robot");
  f.Jump();yield return new WaitForSeconds(.3f);Check(ring.enabled&&ring.GetPosition(0).y<.1f&&f.transform.position.y>.8f&&ring.bounds.extents.x<groundRadius-.05f,"the ring stays on the roof and shrinks while the robot is airborne");
  int pooled=0;foreach(var system in FindObjectsByType<ParticleSystem>(FindObjectsSortMode.None))if(system.name=="Impact sparks")pooled++;for(int i=0;i<40;i++)a.Feedback.Contact(Vector3.up,Vector3.forward,.5f);yield return null;int afterBursts=0;foreach(var system in FindObjectsByType<ParticleSystem>(FindObjectsSortMode.None))if(system.name=="Impact sparks")afterBursts++;
  Check(pooled==a.Feedback.BurstPoolSize&&afterBursts==pooled,"impact effects reuse a fixed particle pool");Check(a.Feedback.MusicPlaying,"the music loop plays");
  yield return new WaitForSecondsRealtime(.3f);var home=a.CameraRig.transform.position;a.CameraRig.Kick(Vector3.right,1);yield return null;Check(Vector3.Distance(home,a.CameraRig.transform.position)<.001f,"screen kick stays off unless enabled");
  OrbitCamera.KickEnabled=true;a.CameraRig.Kick(Vector3.right,1);yield return null;bool moved=Vector3.Distance(home,a.CameraRig.transform.position)>.05f,level=Quaternion.Angle(a.CameraRig.transform.rotation,OrbitCamera.ViewRotation)<.01f;yield return new WaitForSecondsRealtime(.5f);
  Check(moved&&level&&Vector3.Distance(home,a.CameraRig.transform.position)<.005f,"enabled screen kick nudges position only and settles back");OrbitCamera.KickEnabled=kickSetting;
  GameHUD.IntentLabels=true;a.Brain.Enabled=true;a.ResetArena();f.ResetAt(new Vector3(0,.1f,-5));o.ResetAt(new Vector3(0,.1f,5));yield return null;a.Executor.Begin(SemanticAction.APPROACH_OPPONENT,a.Executor.ObserveContext());yield return null;yield return null;
  Check(a.HUD.IntentText(1)=="CLOSING IN","AI intent label shows the action being executed");GameHUD.IntentLabels=false;yield return null;Check(a.HUD.IntentText(1)==null,"AI intent labels can be turned off");GameHUD.IntentLabels=intentSetting;a.StopExecutors("validation");a.Brain.Enabled=false;
  // Stronger rounds: lost props return; the optional rival boost is a visible, recorded rule change.
  a.Match.Phase=RoundPhase.Fight;a.ResetArena();var lost=Arena.Props.Find(x=>x.Kind=="crate");lost.Body.position=new Vector3(0,-4,-14);lost.transform.position=lost.Body.position;yield return new WaitForSeconds(Arena.PropReturnSeconds-1);Check(lost.transform.position.y<-3,"a lost prop stays gone for a while");
  yield return new WaitForSeconds(1.3f);Check(lost.transform.position.y>-1&&lost.FellAt<0,"a lost prop drops back in during the round");yield return new WaitForSeconds(2);var landed=Vector3.ProjectOnPlane(lost.transform.position-lost.Spawn,Vector3.up).magnitude;Check(lost.transform.position.y>-.2f&&lost.transform.position.y<1.5f&&landed<1.5f,"the returned prop lands on the roof at its spawn point");
  System.Collections.Generic.List<float> speeds=new();Action<string> measure=e=>{if(e=="impact")speeds.Add(-1);};f.Event+=measure;
  foreach(float boostLevel in new[]{0f,.5f}){a.Match.RivalBoost=boostLevel;a.Match.ApplyRules();a.ResetArena();o.ResetAt(new Vector3(0,.1f,0));f.ResetAt(new Vector3(0,.1f,1.65f));o.SnapFace(Vector3.forward);yield return new WaitForSeconds(.15f);int before=speeds.Count;o.Push();until=Time.time+1;while(speeds.Count==before&&Time.time<until)yield return null;yield return new WaitForFixedUpdate();speeds[speeds.Count-1]=Vector3.ProjectOnPlane(f.Body.linearVelocity,Vector3.up).magnitude;}
  f.Event-=measure;Check(speeds.Count==2&&speeds[1]>speeds[0]*1.35f,$"rival boost shoves harder ({speeds[0]:0.0} → {(speeds.Count>1?speeds[1]:0):0.0} m/s)");Check(o.Stability>1.25f&&f.Stability==1&&f.PushPower==1,"boost applies only to the orange robot");
  a.Match.TimedRounds=false;a.Match.Practice=false;a.Match.Phase=RoundPhase.Fight;yield return new WaitForSecondsRealtime(.25f);Check(a.HUD.Root.Query<Label>().ToList().Exists(l=>l.text.Contains("+50%")),"the HUD labels the boosted rules");a.Match.RivalBoost=0;a.Match.ApplyRules();a.Match.Practice=true;
  SessionState.SetBool("PG.Combat",false);Debug.Log("COMBAT UPGRADE VALIDATION COMPLETE");EditorApplication.Exit(0);
 }
}
}
#endif
