using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
namespace Playground {
[Serializable] public class EventRecord {public string type,match_id,actor,action,timestamp;public int round_id;public float game_time;}
[Serializable] public class DecisionRecord {
 public string type="decision",match_id,decision_id,request_timestamp,response_timestamp,selected_action,interruption_reason,raw_response;
 public int schema_version=2;public string experiment_id,condition_id,profile_hash,request_state_json,questions_json,execution_status;
 public int round_id;public float game_time,latency_ms,confidence,action_start,action_end;public bool execution_success;
 public string[] available_actions;public StateSnapshot state_snapshot,resulting_state;
}
[Serializable] public class MatchMetadata {public string type="metadata",match_id,game_version,unity_version,model="convaiinnovations/laya",endpoint,profile_hash;public int schema_version=2,wins_required;public ExperimentProfile profile;public string replay="10 Hz sampled transforms; not deterministic physics resimulation";}
[Serializable] public class BodySample {public string id,kind,held_by;public Vector3 position,velocity;public Quaternion rotation;}
[Serializable] public class FrameRecord {public string type="frame",match_id,phase;public int round_id,human_wins,laya_wins;public float game_time;public BodySample[] bodies;}
[Serializable] public class FighterMetrics {public int grabs,throws,hits,pushes,dodges,self_ringouts,opponent_caused_ringouts;public float near_edge_seconds,mean_edge_distance_m;public static FighterMetrics Capture(Fighter f,int selfOuts,int caused)=>new FighterMetrics{grabs=f.Grabs,throws=f.Throws,hits=f.Hits,pushes=f.Pushes,dodges=f.Dodges,self_ringouts=selfOuts,opponent_caused_ringouts=caused,near_edge_seconds=f.EdgeTime,mean_edge_distance_m=f.EdgeSum/Mathf.Max(.01f,f.Samples)};}
[Serializable] public class MatchSummary {public string type="summary",match_id,experiment_id,condition_id;public int human_wins,laya_wins,executed_decisions,failed_requests,stale_responses;public float mean_latency_ms,median_latency_ms,p95_latency_ms;public FighterMetrics human,laya;public int[] action_counts;public string[] action_names=Enum.GetNames(typeof(SemanticAction));}
public class Telemetry:MonoBehaviour {
 public string DirectoryPath,FilePath,MatchId;public int DecisionCount;public float TotalLatency;public readonly int[] Distribution=new int[10];StreamWriter writer;float nextFrame;bool ended;int errors,stale;readonly List<float> latencies=new();ExperimentProfile profile;
 void Awake(){DirectoryPath=Path.Combine(Application.persistentDataPath,"Telemetry");Directory.CreateDirectory(DirectoryPath);}
 public void NewMatch(){if(writer!=null&&!ended)LogEvent("match_abandoned","game","rematch");writer?.Dispose();ended=false;errors=stale=0;latencies.Clear();profile=Arena.Instance.Experiments.Current;MatchId=DateTime.UtcNow.ToString("yyyyMMdd-HHmmss")+"-"+Guid.NewGuid().ToString("N").Substring(0,6);FilePath=Path.Combine(DirectoryPath,MatchId+".jsonl");writer=new StreamWriter(FilePath){AutoFlush=true};DecisionCount=0;TotalLatency=0;Array.Clear(Distribution,0,Distribution.Length);LogEvent("match_start","game","first_to_"+Arena.Instance.Match.WinsRequired);Write(new MatchMetadata{match_id=MatchId,game_version=Application.version,unity_version=Application.unityVersion,endpoint=Arena.Instance.Client.Endpoint,wins_required=Arena.Instance.Match.WinsRequired,profile=profile,profile_hash=profile.Hash()});nextFrame=0;}
 public void LogEvent(string type,string actor,string action){Write(new EventRecord{type=type,match_id=MatchId,round_id=Arena.Instance.Match.Round,actor=actor,action=action,game_time=Time.time,timestamp=DateTime.UtcNow.ToString("O")});}
 public void Write(object record){if(record is DecisionRecord d&&d.match_id==MatchId){if(d.execution_status=="request_error")errors++;if(d.execution_status=="stale")stale++;latencies.Add(d.latency_ms);}try{if(record is DecisionRecord decision&&decision.match_id!=MatchId)File.AppendAllText(Path.Combine(DirectoryPath,decision.match_id+".jsonl"),JsonUtility.ToJson(record)+"\n");else writer?.WriteLine(JsonUtility.ToJson(record));}catch(IOException e){Debug.LogWarning("Telemetry write failed: "+e.Message);}}
 public void Count(DecisionResult result){if(!result.Valid)return;DecisionCount++;TotalLatency+=result.LatencyMs;Distribution[(int)result.Action]++;}
 public void Summary(MatchController match){var path=Path.Combine(DirectoryPath,"matches.csv");bool header=!File.Exists(path);using(var csv=new StreamWriter(path,true)){if(header)csv.WriteLine("match_id,human_wins,laya_wins,human_self_ringouts,laya_self_ringouts,human_throws,laya_throws,human_hits,laya_hits,ai_decisions,mean_ai_latency_ms");csv.WriteLine(string.Join(",",MatchId,match.HumanWins,match.AIWins,match.HumanSelfOuts,match.AISelfOuts,Arena.Instance.Human.Throws,Arena.Instance.AI.Throws,Arena.Instance.Human.Hits,Arena.Instance.AI.Hits,DecisionCount,(TotalLatency/Mathf.Max(1,DecisionCount)).ToString("F1",System.Globalization.CultureInfo.InvariantCulture)));}LogEvent("match_end","game",match.HumanWins>match.AIWins?"Human":"Laya");ended=true;var sorted=latencies.OrderBy(x=>x).ToArray();Write(new MatchSummary{human=FighterMetrics.Capture(Arena.Instance.Human,match.HumanSelfOuts,match.HumanEnvironmentalKOs),laya=FighterMetrics.Capture(Arena.Instance.AI,match.AISelfOuts,match.AIEnvironmentalKOs),match_id=MatchId,experiment_id=profile.experiment_id,condition_id=profile.condition_id,human_wins=match.HumanWins,laya_wins=match.AIWins,executed_decisions=DecisionCount,failed_requests=errors,stale_responses=stale,mean_latency_ms=sorted.Length>0?sorted.Average():0,median_latency_ms=Percentile(sorted,.5f),p95_latency_ms=Percentile(sorted,.95f),action_counts=Distribution});try{MatchExport.Export(FilePath);}catch(Exception e){Debug.LogWarning("Export failed: "+e.Message);}}
 static float Percentile(float[] values,float p)=>values.Length==0?0:values[Mathf.Clamp(Mathf.CeilToInt(values.Length*p)-1,0,values.Length-1)];
 void Update(){var a=Arena.Instance;if(writer==null||!a.Match||a.HUD.Paused||Time.time<nextFrame||ended)return;nextFrame=Time.time+.1f;var bodies=new List<BodySample>();foreach(var f in new[]{a.Human,a.AI})bodies.Add(new BodySample{id=f.Actor,kind="fighter",position=f.transform.position,rotation=f.transform.rotation,velocity=f.Body.linearVelocity,held_by=""});foreach(var p in Arena.Props)bodies.Add(new BodySample{id=p.name,kind=p.Kind,position=p.transform.position,rotation=p.transform.rotation,velocity=p.Body.linearVelocity,held_by=p.Holder?p.Holder.Actor:""});Write(new FrameRecord{match_id=MatchId,round_id=a.Match.Round,phase=a.Match.Phase.ToString(),human_wins=a.Match.HumanWins,laya_wins=a.Match.AIWins,game_time=Time.time,bodies=bodies.ToArray()});}
 void OnDestroy(){writer?.Dispose();}
}
}
