using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;
namespace Playground {
[Serializable] public class EventRecord {public string type,match_id,actor,action,timestamp;public int round_id;public float game_time;}
[Serializable] public class DecisionRecord {
 public string type="decision",match_id,decision_id,request_timestamp,response_timestamp,selected_action,interruption_reason,raw_response;
 public int schema_version=3;public string actor,provider,model,response_model,inference_device;public float inference_ms;public string experiment_id,condition_id,profile_hash,request_state_json,questions_json,execution_status;
 public int round_id;public float game_time,latency_ms,confidence,action_start,action_end;public bool execution_success;
 public string[] available_actions;public StateSnapshot state_snapshot,resulting_state;
}
[Serializable] public class Participant {public string actor,controller,model,endpoint;}
[Serializable] public class AIStatistics {public string actor;public int executed_decisions,failed_requests,stale_responses;public float total_latency_ms;public int[] action_counts=new int[10];}
[Serializable] public class MatchMetadata {public string type="metadata",match_id,game_version,unity_version,model="convaiinnovations/laya",endpoint,profile_hash;public string matchup;public Participant[] participants;public int schema_version=3,wins_required;public ExperimentProfile profile;public string replay="10 Hz sampled transforms; not deterministic physics resimulation";}
[Serializable] public class BodySample {public string id,kind,held_by,slot;public Vector3 position,velocity;public Quaternion rotation;}
[Serializable] public class FrameRecord {public string type="frame",match_id,phase;public int round_id,human_wins,laya_wins,left_wins,right_wins;public float game_time;public BodySample[] bodies;}
[Serializable] public class FighterMetrics {public int grabs,throws,hits,pushes,dodges,self_ringouts,opponent_caused_ringouts;public float near_edge_seconds,mean_edge_distance_m;public static FighterMetrics Capture(Fighter f,int selfOuts,int caused)=>new FighterMetrics{grabs=f.Grabs,throws=f.Throws,hits=f.Hits,pushes=f.Pushes,dodges=f.Dodges,self_ringouts=selfOuts,opponent_caused_ringouts=caused,near_edge_seconds=f.EdgeTime,mean_edge_distance_m=f.EdgeSum/Mathf.Max(.01f,f.Samples)};}
[Serializable] public class MatchSummary {public string type="summary",match_id,experiment_id,condition_id,left_actor,right_actor;public AIStatistics[] ai_players;public int schema_version=3,left_wins,right_wins;public FighterMetrics left,right;public int human_wins,laya_wins,executed_decisions,failed_requests,stale_responses;public float mean_latency_ms,median_latency_ms,p95_latency_ms;public FighterMetrics human,laya;public int[] action_counts;public string[] action_names=Enum.GetNames(typeof(SemanticAction));}
public class Telemetry:MonoBehaviour {
 public string DirectoryPath,FilePath,MatchId;public int DecisionCount;public float TotalLatency;public readonly int[] Distribution=new int[10];TelemetryWriter writer;float nextFrame;bool ended;int errors,stale;readonly List<float> latencies=new();ExperimentProfile profile;readonly Dictionary<string,AIStatistics> actorStats=new();
 public AIStatistics StatsFor(string actor){if(!actorStats.TryGetValue(actor,out var stats)){stats=new AIStatistics{actor=actor};actorStats[actor]=stats;}return stats;}
 public Participant[] Participants(){var a=Arena.Instance;return new[]{new Participant{actor=a.LeftName,controller=a.Spectating?"Laya":"Human",model=a.Spectating?a.LeftClient.Model:null,endpoint=a.Spectating?a.LeftClient.Endpoint:null},new Participant{actor=a.RightName,controller=a.Client.Provider.ToString(),model=a.Client.Model,endpoint=a.Client.Endpoint}};}
 void Awake(){DirectoryPath=Path.Combine(Application.persistentDataPath,"Telemetry");Directory.CreateDirectory(DirectoryPath);writer=new TelemetryWriter();}
 public void NewMatch(){if(MatchId!=null&&!ended)LogEvent("match_abandoned","game","rematch");ended=false;errors=stale=0;actorStats.Clear();latencies.Clear();profile=Arena.Instance.Experiments.Current;MatchId=DateTime.UtcNow.ToString("yyyyMMdd-HHmmss")+"-"+Guid.NewGuid().ToString("N").Substring(0,6);FilePath=Path.Combine(DirectoryPath,MatchId+".jsonl");DecisionCount=0;TotalLatency=0;Array.Clear(Distribution,0,Distribution.Length);LogEvent("match_start","game","first_to_"+Arena.Instance.Match.WinsRequired);Write(new MatchMetadata{participants=Participants(),matchup=Arena.Instance.Setup.Mode.ToString(),model=Arena.Instance.Client.Model,match_id=MatchId,game_version=Application.version,unity_version=Application.unityVersion,endpoint=Arena.Instance.Client.Endpoint,wins_required=Arena.Instance.Match.WinsRequired,profile=profile,profile_hash=profile.Hash()});nextFrame=0;}
 public void LogEvent(string type,string actor,string action){Write(new EventRecord{type=type,match_id=MatchId,round_id=Arena.Instance.Match.Round,actor=actor,action=action,game_time=Time.time,timestamp=DateTime.UtcNow.ToString("O")});}
 public void Write(object record){if(record is DecisionRecord d&&d.match_id==MatchId){if(d.execution_status=="request_error"){errors++;StatsFor(d.actor??"Laya").failed_requests++;}if(d.execution_status=="stale"){stale++;StatsFor(d.actor??"Laya").stale_responses++;}latencies.Add(d.latency_ms);}string path=record is DecisionRecord decision&&decision.match_id!=MatchId?Path.Combine(DirectoryPath,decision.match_id+".jsonl"):FilePath;if(path!=null)writer.Write(path,JsonUtility.ToJson(record));}
 public string RecordingError=>writer?.Error;
 public Task<string[]> SnapshotAsync(string path)=>writer.SnapshotAsync(path);
 public Task FlushAsync()=>writer.FlushAsync();
 public void Flush()=>FlushAsync().GetAwaiter().GetResult();
 public void Count(DecisionResult result,string actor="Laya"){if(!result.Valid)return;var stats=StatsFor(actor);stats.executed_decisions++;stats.total_latency_ms+=result.LatencyMs;stats.action_counts[(int)result.Action]++;DecisionCount++;TotalLatency+=result.LatencyMs;Distribution[(int)result.Action]++;}
 public void Summary(MatchController match){var path=Path.Combine(DirectoryPath,"matches-v3.csv");writer.Csv(path,"match_id,left_actor,right_actor,left_wins,right_wins,left_self_ringouts,right_self_ringouts,left_throws,right_throws,left_hits,right_hits,ai_decisions,mean_ai_latency_ms",string.Join(",",MatchId,Arena.Instance.LeftName,Arena.Instance.RightName,match.HumanWins,match.AIWins,match.HumanSelfOuts,match.AISelfOuts,Arena.Instance.Human.Throws,Arena.Instance.AI.Throws,Arena.Instance.Human.Hits,Arena.Instance.AI.Hits,DecisionCount,(TotalLatency/Mathf.Max(1,DecisionCount)).ToString("F1",System.Globalization.CultureInfo.InvariantCulture)));LogEvent("match_end","game",match.HumanWins>match.AIWins?Arena.Instance.LeftName:Arena.Instance.RightName);ended=true;var sorted=latencies.OrderBy(x=>x).ToArray();Write(new MatchSummary{left_wins=match.HumanWins,right_wins=match.AIWins,left=FighterMetrics.Capture(Arena.Instance.Human,match.HumanSelfOuts,match.HumanEnvironmentalKOs),right=FighterMetrics.Capture(Arena.Instance.AI,match.AISelfOuts,match.AIEnvironmentalKOs),left_actor=Arena.Instance.LeftName,right_actor=Arena.Instance.RightName,ai_players=actorStats.Values.ToArray(),human=FighterMetrics.Capture(Arena.Instance.Human,match.HumanSelfOuts,match.HumanEnvironmentalKOs),laya=FighterMetrics.Capture(Arena.Instance.AI,match.AISelfOuts,match.AIEnvironmentalKOs),match_id=MatchId,experiment_id=profile.experiment_id,condition_id=profile.condition_id,human_wins=match.HumanWins,laya_wins=match.AIWins,executed_decisions=DecisionCount,failed_requests=errors,stale_responses=stale,mean_latency_ms=sorted.Length>0?sorted.Average():0,median_latency_ms=Percentile(sorted,.5f),p95_latency_ms=Percentile(sorted,.95f),action_counts=Distribution});ExportCompleted(FilePath,Path.Combine(Application.streamingAssetsPath,"inspector-template.html"));}
 async void ExportCompleted(string path,string template){try{var snapshot=await SnapshotAsync(path);await Task.Run(()=>MatchExport.Export(path,template,snapshot));}catch(Exception e){Debug.LogWarning("Export failed: "+e.Message);}}
 static float Percentile(float[] values,float p)=>values.Length==0?0:values[Mathf.Clamp(Mathf.CeilToInt(values.Length*p)-1,0,values.Length-1)];
 void Update(){var a=Arena.Instance;if(FilePath==null||!a.Match||a.HUD.Paused||Time.time<nextFrame||ended)return;nextFrame=Time.time+.1f;var bodies=new List<BodySample>();foreach(var f in new[]{a.Human,a.AI})bodies.Add(new BodySample{id=f.Actor,slot=f==a.Human?"left":"right",kind="fighter",position=f.transform.position,rotation=f.transform.rotation,velocity=f.Body.linearVelocity,held_by=""});foreach(var p in Arena.Props)bodies.Add(new BodySample{id=p.name,kind=p.Kind,position=p.transform.position,rotation=p.transform.rotation,velocity=p.Body.linearVelocity,held_by=p.Holder?p.Holder.Actor:""});Write(new FrameRecord{match_id=MatchId,round_id=a.Match.Round,phase=a.Match.Phase.ToString(),left_wins=a.Match.HumanWins,right_wins=a.Match.AIWins,human_wins=a.Match.HumanWins,laya_wins=a.Match.AIWins,game_time=Time.time,bodies=bodies.ToArray()});}
 void OnDestroy(){writer?.Dispose();}
}
}
